<?php
// Bloxx - Open Source Content Management System
//
// Copyright (c) 2002 - 2005 The Bloxx Team. All rights reserved.
//
// Bloxx is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation; either version 2 of the License, or
// (at your option) any later version.
//
// Bloxx is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.

// You should have received a copy of the GNU General Public License
// along with Bloxx; if not, write to the Free Software
// Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
//
// Authors: Silas Francisco <draft@dog.kicks-ass.net>
//			Telmo Menezes	<telmo@cognitiva.net>
//
// $Id: install.php,v 1.10 2005-06-22 20:05:29 tmenezes Exp $
 
require_once 'DB.php';
require_once 'PEAR.php';

$bloxxCoreVersion = '0.8';

if (!file_exists('defines.php')) {

	if (isset($_POST['username']) && isset($_POST['password']) 
		&& isset($_POST['host']) && isset($_POST['database']) && isset($_POST['initfile'])) {

		$hostDSN     = 'mysql://' . $_POST['username'] . ':' . $_POST['password'] . '@' . $_POST['host'];	
		$databaseDSN = $hostDSN . '/' . $_POST['database'];
					
		$buffer = "<?php\n\n// Autogenerated file by wizard.php\n\n"
				. "define('DATABASE_DSN', '" . $databaseDSN . "');\n"
				. "define('MAIN_DIR', '');\n"
				. "define('CORE_DIR', MAIN_DIR . 'core/');\n"
				. "define('INIT_FILE', MAIN_DIR . '" . $_POST['initfile'] . "');\n"
				. "define('MODS_DIR', MAIN_DIR . 'mods/');\n"
				. "define('LANG_DIR', MAIN_DIR . 'lang/');\n"
				. "define('JAVASCRIPT_DIR', MAIN_DIR . 'javascript/');\n"
				. "define('ENUM_DIR', MAIN_DIR . 'enums/');\n\n"
				. "define('BLOXX_CORE_VERSION', '". $bloxxCoreVersion . "');\n?>\n"; 

		$mysqlHost = DB::connect($hostDSN);
		if (DB::isError($mysqlHost)) {
					
			echo $mysqlHost->toString();
		}
		else {

			if (isset($_POST['overwritedb'])) {

				$mysqlHost->query('DROP DATABASE ' . $_POST['database']);
			}
					
			$result = $mysqlHost->query('CREATE DATABASE ' . $_POST['database']);
			if (DB::isError($result)) {
					
				echo $result->toString();
			}
			else {
				
				$defines = fopen('defines.php', 'x');
				if ($defines !== FALSE) {
			
					if (fwrite($defines, $buffer) !== FALSE) {
									
						bloxxInstall();
						bloxxInstallMods();
					}

					fclose($defines);
				}
			}
		}
	} 
	else {

		$html_out = '<html><body>';
		$html_out .= 'You are about to install bloxx <br>'
					.'bla bla bla, bla bla bla <br>';
					
		$html_out .= '<form enctype="multipart/form-data"';
		$html_out .= ' name="' . 'wizard' . '"';
		$html_out .= ' action="install.php';
		$html_out .=  '" method="POST">';

		$size = '10';
		$maxlengh = '255';
		$type = 'text';

		$html_out .= 'mysql://
    	<input name="' . 'username' . '" type="' . $type . '" value="' . '' .
    	'" size="' . $size . '" maxlength="' . $maxlength . '">';
                
    	$html_out .= ':
    	<input name="' . 'password' . '" type="' . 'password' . '" value="' . '' .
    	'" size="' . $size . '" maxlength="' . $maxlength . '">';
                
    	$html_out .= '@
    	<input name="' . 'host' . '" type="' . $type . '" value="' . 'localhost' .
    	'" size="' . '20' . '" maxlength="' . $maxlength . '">';
    	
    	$html_out .= '/
    	<input name="' . 'database' . '" type="' . $type . '" value="' . 'test' .
    	'" size="' . $size . '" maxlength="' . $maxlength . '">';
                
    	$html_out .= 'Init File:
    	<select name="initfile">';
    	
    	$dh = opendir('init/');

		while (($file = readdir($dh)) !== false) 
		{
    	    if (!is_dir($file) && ($file != '.') && ($file != '..'))
    	    {
    	    	$html_out .= '<option value="' . 'init/' . $file . '"' . '>' . $file;
        	}
		}

		closedir($dh);

		$html_out .= '</select>';
		                
    	$html_out .= '
    	<input type="SUBMIT" name="submit" value="' . 'Install' . '">
    	';
    	
    	$html_out .= '<br>
    	<input name="' . 'overwritedb' . '" type="checkbox"> overwrite old database';
    	
                
		$html_out .= '</form></body></html>';

		echo $html_out;
	}
}

function bloxxInstall() 
{
	require_once('defines.php');
	require_once('functions.php');
	include_once(CORE_DIR.'bloxx_page.php');
	include_once(CORE_DIR.'bloxx_modulemanager.php');
	include_once(CORE_DIR.'bloxx_config.php');
	include_once(CORE_DIR.'bloxx_logs.php');
	include_once(CORE_DIR.'bloxx_session.php');
	include_once(CORE_DIR.'bloxx_identity.php');
	include_once(CORE_DIR.'bloxx_role.php');
	include_once(CORE_DIR.'bloxx_admin.php');
	include_once(CORE_DIR.'bloxx_style.php');
	include_once(CORE_DIR.'bloxx_moduletemplate.php');
	include_once(CORE_DIR.'bloxx_resource.php');
	include_once(CORE_DIR.'bloxx_headerfooter.php');
	include_once(CORE_DIR.'bloxx_language.php');
	include_once(CORE_DIR.'bloxx_usergroup.php');
	include_once(CORE_DIR.'bloxx_grouplink.php');
	include_once(CORE_DIR.'bloxx_workflow.php');
	include_once(CORE_DIR.'bloxx_state.php');
	include_once(CORE_DIR.'bloxx_list.php');

	$module_manager = new Bloxx_ModuleManager();
	$module_manager->install(false);
	$system = new Bloxx_Config();
	$system->install(false);
	$language = new Bloxx_Language();
	$language->install(false);
	$language->afterInstall();
	$page = new Bloxx_Page();
	$page->install(false);	
	$user = new Bloxx_Identity();
	$user->install(false);
	$admin = new Bloxx_Admin();
	$admin->install(false);
	$logs = new Bloxx_Logs();
	$logs->install(false);
	$session = new Bloxx_Session();
	$session->install(false);
	$style = new Bloxx_Style();
	$style->install(false);
	$mt = new Bloxx_ModuleTemplate();
	$mt->install(false);
	$headerfooter = new Bloxx_HeaderFooter();
	$headerfooter->install(false);
	$resource = new Bloxx_Resource();
	$resource->install(false);
	$group = new Bloxx_UserGroup();
	$group->install(false);
	$grouplink = new Bloxx_GroupLink();
	$grouplink->install(false);
	$wf = new Bloxx_Workflow();
	$wf->install(false);
	$state = new Bloxx_State();
	$state->install(false);
	$list = new Bloxx_List();
	$list->install(false);

	$module_manager->afterInstall();
	$system->afterInstall();
	$page->afterInstall();	
	$user->afterInstall();
	$admin->afterInstall();
	$logs->afterInstall();
	$session->afterInstall();
	$style->afterInstall();
	$mt->afterInstall();
	$headerfooter->afterInstall();
	$resource->afterInstall();
	$group->afterInstall();
	$grouplink->afterInstall();
	$wf->afterInstall();
	$state->afterInstall();
	$list->afterInstall();
	
	$role = new Bloxx_Role();
	$role->install(false);
	$role->afterInstall();
}

function bloxxInstallMods() 
{
	require_once('defines.php');
	require_once('functions.php');

	$dh = opendir(MODS_DIR);

	while (($file = readdir($dh)) !== false) 
	{
    	    if (is_file(MODS_DIR . $file) && ($file != '.') && ($file != '..'))
    	    {
        	        include_once(MODS_DIR . $file);

            	    $mod_name = substr($file, 0, -4);
                	$mod = new $mod_name();
                	$mod->install(false);
        	}
	}

	closedir($dh);

	$dh = opendir(MODS_DIR);

	while (($file = readdir($dh)) !== false) 
	{
    	    if(is_file(MODS_DIR . $file) && ($file != '.') && ($file != '..')){
        
        		$mod_name = substr($file, 0, -4);
           		$mod = new $mod_name();
               	$mod->afterInstall();
        	}
	}

	closedir($dh);
}
?>
