<?php
// Bloxx - Open Source Content Management System
//
// Copyright (c) 2002 - 2005 The Bloxx Team. All rights reserved.
//
// Bloxx is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation; either version 2 of the License, or
// (at your option) any later version.
//
// Bloxx is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.

// You should have received a copy of the GNU General Public License
// along with Bloxx; if not, write to the Free Software
// Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
//
// Authors: Silas Francisco <draft@dog.kicks-ass.net>
//			Telmo Menezes	<telmo@cognitiva.net>
//
// $Id: install.php,v 1.11 2005-08-08 16:38:33 tmenezes Exp $

require_once('core/bloxx_error.php');
require_once('core/bloxx_dbobject.php');
 
global $BLOXX_ERROR;
$BLOXX_ERROR = new Bloxx_Error(ERROR_REPORT_MODE_PRINT_SENSITIVE, WARNING_REPORT_MODE_PRINT, DEBUG_REPORT_MODE_PRINT);

$bloxxCoreVersion = '0.8';

if (!file_exists('defines.php'))
{

	if (isset($_POST['username']) && isset($_POST['password']) 
		&& isset($_POST['host']) && isset($_POST['database']) && isset($_POST['initfile']))
	{
		$hostDSN     = 'mysql://' . $_POST['username'] . ':' . $_POST['password'] . '@' . $_POST['host'];	
		$databaseDSN = $hostDSN . '/' . $_POST['database'];
					
		$buffer = "<?php\n\n// Autogenerated file by wizard.php\n\n"
				. "define('DATABASE_DSN', '" . $databaseDSN . "');\n"
				. "define('MAIN_DIR', '');\n"
				. "define('CORE_DIR', MAIN_DIR . 'core/');\n"
				. "define('INIT_FILE', MAIN_DIR . '" . $_POST['initfile'] . "');\n"
				. "define('MODS_DIR', MAIN_DIR . 'mods/');\n"
				. "define('LANG_DIR', MAIN_DIR . 'lang/');\n"
				. "define('JAVASCRIPT_DIR', MAIN_DIR . 'javascript/');\n"
				. "define('THIRD_PARTY_DIR', MAIN_DIR . 'third_party/');\n"
				. "define('ENUM_DIR', MAIN_DIR . 'enums/');\n\n"
				. "define('BLOXX_CORE_VERSION', '". $bloxxCoreVersion . "');\n?>\n"; 

		// We use the hostDSN because the database may not exist yet.		
		$db = new Bloxx_DBObject($hostDSN);
		
		global $DB_CONNECTION;
		if (!$DB_CONNECTION)
		{			
			// DB Connection failed.
		}
		else
		{
			if (isset($_POST['overwritedb']))
			{
				
				$db->dropDatabase($_POST['database']);
			}
					
			if (!$db->createDatabase($_POST['database']))
			{
					
				// Error creating database
			}
			else
			{	
				// Don't use the databaseless connection from now on.
				$DB_CONNECTION = false;
				
				$defines = fopen('defines.php', 'x');
				if ($defines !== FALSE)
				{
					if (fwrite($defines, $buffer) !== FALSE)
					{
						bloxxInstall();
						bloxxInstallMods();
					}

					fclose($defines);
				}
			}
		}
		
		//Goto main page
		header("Location: index.php");
	} 
	else
	{
		echo renderInstallForm();
	}
}

function bloxxInstall() 
{
	require_once('defines.php');
	require_once('functions.php');
	include_once(CORE_DIR.'bloxx_page.php');
	include_once(CORE_DIR.'bloxx_modulemanager.php');
	include_once(CORE_DIR.'bloxx_config.php');
	include_once(CORE_DIR.'bloxx_logs.php');
	include_once(CORE_DIR.'bloxx_session.php');
	include_once(CORE_DIR.'bloxx_identity.php');
	include_once(CORE_DIR.'bloxx_role.php');
	include_once(CORE_DIR.'bloxx_admin.php');
	include_once(CORE_DIR.'bloxx_style.php');
	include_once(CORE_DIR.'bloxx_moduletemplate.php');
	include_once(CORE_DIR.'bloxx_resource.php');
	include_once(CORE_DIR.'bloxx_headerfooter.php');
	include_once(CORE_DIR.'bloxx_language.php');
	include_once(CORE_DIR.'bloxx_usergroup.php');
	include_once(CORE_DIR.'bloxx_grouplink.php');
	include_once(CORE_DIR.'bloxx_workflow.php');
	include_once(CORE_DIR.'bloxx_state.php');
	include_once(CORE_DIR.'bloxx_list.php');

	$module_manager = new Bloxx_ModuleManager();
	$module_manager->install(false);
	$system = new Bloxx_Config();
	$system->install(false);
	$language = new Bloxx_Language();
	$language->install(false);
	$language->afterInstall();
	$page = new Bloxx_Page();
	$page->install(false);	
	$user = new Bloxx_Identity();
	$user->install(false);
	$admin = new Bloxx_Admin();
	$admin->install(false);
	$logs = new Bloxx_Logs();
	$logs->install(false);
	$session = new Bloxx_Session();
	$session->install(false);
	$style = new Bloxx_Style();
	$style->install(false);
	$mt = new Bloxx_ModuleTemplate();
	$mt->install(false);
	$headerfooter = new Bloxx_HeaderFooter();
	$headerfooter->install(false);
	$resource = new Bloxx_Resource();
	$resource->install(false);
	$group = new Bloxx_UserGroup();
	$group->install(false);
	$grouplink = new Bloxx_GroupLink();
	$grouplink->install(false);
	$wf = new Bloxx_Workflow();
	$wf->install(false);
	$state = new Bloxx_State();
	$state->install(false);
	$list = new Bloxx_List();
	$list->install(false);

	$module_manager->afterInstall();
	$system->afterInstall();
	$page->afterInstall();	
	$user->afterInstall();
	$admin->afterInstall();
	$logs->afterInstall();
	$session->afterInstall();
	$style->afterInstall();
	$mt->afterInstall();
	$headerfooter->afterInstall();
	$resource->afterInstall();
	$group->afterInstall();
	$grouplink->afterInstall();
	$wf->afterInstall();
	$state->afterInstall();
	$list->afterInstall();
	
	$role = new Bloxx_Role();
	$role->install(false);
	$role->afterInstall();
}

function bloxxInstallMods() 
{
	require_once('defines.php');
	require_once('functions.php');

	$dh = opendir(MODS_DIR);

	while (($file = readdir($dh)) !== false) 
	{
    	    if (is_file(MODS_DIR . $file) && ($file != '.') && ($file != '..'))
    	    {
        	        include_once(MODS_DIR . $file);

            	    $mod_name = substr($file, 0, -4);
                	$mod = new $mod_name();
                	$mod->install(false);
        	}
	}

	closedir($dh);

	$dh = opendir(MODS_DIR);

	while (($file = readdir($dh)) !== false) 
	{
    	    if(is_file(MODS_DIR . $file) && ($file != '.') && ($file != '..')){
        
        		$mod_name = substr($file, 0, -4);
           		$mod = new $mod_name();
               	$mod->afterInstall();
        	}
	}

	closedir($dh);
}

function renderInstallForm()
{
	$html_out = '
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "DTD/xhtml1-transitional.dtd">			
<html lang="EN">
<head>
<title>Bloxx Install Tool</title>
</head>
<body>
<link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
<link rel="stylesheet" href="install.css" type="text/css" />

<div id="left_bar">

</div>

<div id="right_bar" class="normal">
<h1>Bloxx Install Tool</h1>

<p>
You are about to install Bloxx, the open source web framework / content management system.
To install Bloxx you must have a working account with sufficient permissions on a database server.
</p>

<p><strong>Note:</strong> Bloxx currently supports MySQL only.</p>
					
<form enctype="multipart/form-data" name="wizard" action="install.php" method="POST">

<h2>Database account username</h2>
<input name="username" type="text" value="" size="20" maxlength="255">
<br /><br />
<h2>Database account password</h2>
<input name="password" type="password" value="" size="20" maxlength="255">
<br /><br />    
<h2>Database host</h2>
<input name="host" type="text" value="localhost" size="20" maxlength="255">
<br /><br />          
<h2>Database name</h2>
<input name="database" type="text" value="demo" size="20" maxlength="255">
<br /><br />          
<h2>Init File</h2>
<select name="initfile">
	';
    	
	$dh = opendir('init/');

	while (($file = readdir($dh)) !== false) 
	{
		if (!is_dir($file) && ($file != '.') && ($file != '..'))
		{
			$html_out .= '<option value="' . 'init/' . $file . '"' . '>' . $file;
		}
	}

	closedir($dh);

	$html_out .= '

</select>
<br /><br />
<input name="overwritedb" type="checkbox">
Overwrite old database?
<br /><br />
<input type="SUBMIT" name="submit" value="Install">
</form>

</div>

</body></html>
	';
		
	return $html_out;
}
?>
