<?php
/*
 * Created on Feb 20, 2005
 *
 * draft
 * 
 */

$bloxxCoreVersion = 0.6;

if(!file_exists('defines.php')) {
 
	if(isset($_POST['username']) && isset($_POST['password']) 
		&& isset($_POST['database']) && isset($_POST['initfile'])) {
	
		$buffer = "<?php\n\n// Autogenerated file by wizard.php\n\n"
				. "define('DATABASE_DSN', '"
				. "mysql://" . $_POST['username'] . ":" . $_POST['password'] . "@" . $_POST['database'] . "');\n"
				. "define('MAIN_DIR', '');\n"
				. "define('CORE_DIR', MAIN_DIR . 'core/');\n"
				. "define('INIT_FILE', MAIN_DIR . '" . $_POST['initfile'] . "');\n"
				. "define('MODS_DIR', MAIN_DIR . 'mods/');\n"
				. "define('LANG_DIR', MAIN_DIR . 'lang/');\n"
				. "define('JAVASCRIPT_DIR', MAIN_DIR . 'javascript/');\n"
				. "define('ENUM_DIR', MAIN_DIR . 'enums/');\n\n"
				. "define('BLOXX_CORE_VERSION', '". $bloxxCoreVersion . "');\n?>\n"; 

		$defines = fopen('defines.php', 'x');
		if($defines !== FALSE) {
			
			if(fwrite($defines, $buffer) !== FALSE) {
			
				include('install.php');
				bloxxInstall();
			}

			fclose($defines);
		}

	} else {

		$html_out = '<html><body>';
		$html_out .= 'You are about to install bloxx, before hit install button you must '
					.'create database in your mysql server. <br>Ex: create database test;<br>'
					.'bla bla bla, bla bla bla <br>';
					
		$html_out .= '<form enctype="multipart/form-data"';
		$html_out .= ' name="' . 'wizard' . '"';
		$html_out .= ' action="wizard.php';
		$html_out .=  '" method="POST">';

		$size = 10;
		$maxlengh = 255;
		$type = 'text';

		$html_out .= 'mysql://
    	<input name="' . 'username' . '" type="' . $type . '" value="' . '' .
    	'" size="' . $size . '" maxlength="' . $maxlength . '">';
                
    	$html_out .= ':
    	<input name="' . 'password' . '" type="' . 'password' . '" value="' . '' .
    	'" size="' . $size . '" maxlength="' . $maxlength . '">';
                
    	$html_out .= '@
    	<input name="' . 'database' . '" type="' . $type . '" value="' . 'localhost/test' .
    	'" size="' . '30' . '" maxlength="' . $maxlength . '">';
                
    	$html_out .= 'Init File:
    	<input name="' . 'initfile' . '" type="' . $type . '" value="' . 'init/test.bloxx' .
    	'" size="' . '30' . '" maxlength="' . $maxlength . '">';
                
    	$html_out .= '
    	<input type="SUBMIT" name="submit" value="' . 'Install' . '">
    	';
                
		$html_out .= '</form></body></html>';

		echo $html_out;
	}
}
?>
