<?php
// Bloxx - Open Source Content Management System
//
// Copyright (c) 2002 - 2005 The Bloxx Team. All rights reserved.
//
// Bloxx is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation; either version 2 of the License, or
// (at your option) any later version.
//
// Bloxx is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.

// You should have received a copy of the GNU General Public License
// along with Bloxx; if not, write to the Free Software
// Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
//
// Authors: Silas Francisco <draft@dog.kicks-ass.net>
//
//
// $Id: wizard.php,v 1.3 2005-02-22 22:10:38 secretdraft Exp $
 
require_once 'DB.php';
require_once 'PEAR.php';

$bloxxCoreVersion = '0.6';

if (!file_exists('defines.php')) {

	if (isset($_POST['username']) && isset($_POST['password']) 
		&& isset($_POST['host']) && isset($_POST['database']) && isset($_POST['initfile'])) {

		$hostDSN     = 'mysql://' . $_POST['username'] . ':' . $_POST['password'] . '@' . $_POST['host'];	
		$databaseDSN = $hostDSN . '/' . $_POST['database'];
					
		$buffer = "<?php\n\n// Autogenerated file by wizard.php\n\n"
				. "define('DATABASE_DSN', '" . $databaseDSN . "');\n"
				. "define('MAIN_DIR', '');\n"
				. "define('CORE_DIR', MAIN_DIR . 'core/');\n"
				. "define('INIT_FILE', MAIN_DIR . '" . $_POST['initfile'] . "');\n"
				. "define('MODS_DIR', MAIN_DIR . 'mods/');\n"
				. "define('LANG_DIR', MAIN_DIR . 'lang/');\n"
				. "define('JAVASCRIPT_DIR', MAIN_DIR . 'javascript/');\n"
				. "define('ENUM_DIR', MAIN_DIR . 'enums/');\n\n"
				. "define('BLOXX_CORE_VERSION', '". $bloxxCoreVersion . "');\n?>\n"; 

		$mysqlHost = DB::connect($hostDSN);
		if (DB::isError($mysqlHost)) {
					
			echo $mysqlHost->toString();
		}
		else {

			if (isset($_POST['overwritedb']) && ($_POST['overwritedb'] == 1)) {
				
				$mysqlHost->query('DROP DATABASE ' . $_POST['database']);
			}
					
			$result = $mysqlHost->query('CREATE DATABASE ' . $_POST['database']);
			if (DB::isError($result)) {
					
				echo $result->toString();
			}
			else {
				
				$defines = fopen('defines.php', 'x');
				if ($defines !== FALSE) {
			
					if (fwrite($defines, $buffer) !== FALSE) {
			
						include('install.php');
						bloxxInstall();
					}

					fclose($defines);
				}
			}
		}
	} 
	else {

		$html_out = '<html><body>';
		$html_out .= 'You are about to install bloxx <br>'
					.'bla bla bla, bla bla bla <br>';
					
		$html_out .= '<form enctype="multipart/form-data"';
		$html_out .= ' name="' . 'wizard' . '"';
		$html_out .= ' action="wizard.php';
		$html_out .=  '" method="POST">';

		$size = '10';
		$maxlengh = '255';
		$type = 'text';

		$html_out .= 'mysql://
    	<input name="' . 'username' . '" type="' . $type . '" value="' . '' .
    	'" size="' . $size . '" maxlength="' . $maxlength . '">';
                
    	$html_out .= ':
    	<input name="' . 'password' . '" type="' . 'password' . '" value="' . '' .
    	'" size="' . $size . '" maxlength="' . $maxlength . '">';
                
    	$html_out .= '@
    	<input name="' . 'host' . '" type="' . $type . '" value="' . 'localhost' .
    	'" size="' . '20' . '" maxlength="' . $maxlength . '">';
    	
    	$html_out .= '/
    	<input name="' . 'database' . '" type="' . $type . '" value="' . 'test' .
    	'" size="' . $size . '" maxlength="' . $maxlength . '">';
                
    	$html_out .= 'Init File:
    	<input name="' . 'initfile' . '" type="' . $type . '" value="' . 'init/test.bloxx' .
    	'" size="' . '30' . '" maxlength="' . $maxlength . '">';
                
    	$html_out .= '
    	<input type="SUBMIT" name="submit" value="' . 'Install' . '">
    	';
    	
    	$html_out .= '<br>
    	<input name="' . 'overwritedb' . '" type="checkbox" value="1"> overwrite old database';
    	
                
		$html_out .= '</form></body></html>';

		echo $html_out;
	}
}
?>
